name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask application
        run: |
          nohup python run.py &
          sleep 5  # Give the server some time to start

      - name: Check if Flask app is running
        run: |
          curl --fail http://127.0.0.1:5000 || exit 1

      - name: Run tests
        run: |
          pytest  # or other tests that make HTTP requests to the running app

      - name: Stop Flask application
        run: |
          kill $(ps aux | grep '[p]ython run.py' | awk '{print $2}')