name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask application
        run: |
          nohup python run.py &
          echo "Flask application started"
          sleep 10  # Wait for the Flask app to start

      - name: Verify Flask application is running
        run: |
          curl --fail http://127.0.0.1:5000 || exit 1

      - name: Run tests
        run: |
          python -m pytest -v

    #   - name: Stop Flask application
    #     run: |
    #       pkill -f 'python run.py'